export const CHANGE_SINGER_LIST = 'recommend/CHANGE_SINGER_LIST';
export const CHANGE_LIST_OFFSET = 'recommend/CHANGE_LIST_OFFSET';
export const CHANGE_ENTER_LOADING = 'recommend/CHANGE_ENTER_LOADING';
export const CHANGE_PULL_UP_LOADING = 'recommend/CHANGE_PULL_UP_LOADING';
export const CHANGE_PULL_DOWN_LOADING = 'recommend/CHANGE_PULL_DOWN_LOADING ';